# Generated by Django 5.2.7 on 2025-10-06 04:34

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid_until',
            field=models.DateField(default=tenants.models.get_default_paid_until),
        ),
    ]
